### ISSUE TITLE
style matrix (2.3)

### ISSUE THREAD

**Issue by pain-text-format** [pain-text-format/kksubs#17]
styles.yaml is still very annoying to configure, unfortunately most config files don't support for loops. Use matrices (more like jagged arrays) to speed up configuration via "multiplicative inheritance" (avoid having to write python scripts to generate style files, or worse write the styles by hand)

```
- matrix:
  - - style_id: style-1
    - style_id: style-2
  - - style_id: style_3
    - style_id: style_4

# is equivalent to

- style_id: style-1
- style_id: style-2
- style_id: style-3
- style_id: style-4
- style_id: style_3-style-1(style-1)
- style_id: style_3-style-2(style-2)
- style_id: style_4-style-1(style-1)
- style_id: style_4-style-2(style-2)
```
Can combine multiple rows (though flatter rows will give shorter names)
```
- matrix
  - row-1
  - row-2
  - ...
  - row-n
```

Now add some commonly used rows as aliases
```
- matrix:
  - row: grid4-complete # a built-in row covering every grid4 configuration

# equivalent to

- style_id: "00"
  box_data.grid4: [0, 0]
- style_id: "01"
  box_data.grid4: [0, 1]
- ...
- style_id: "44"
  box_data.grid4: [4, 4]
```

allows
```
- matrix:
  - - style_id: character
  - row: grid4-complete

# equivalent to

- style_id: "00"
- ...
- style_id: "44"
- style_id: character
- style_id: character-00(character, 00)
- style_id: character-01(character, 01)
- ...
- style_id: character-44(character, 44)
```
Probably also a good idea to add a 'nickname' for a style, so we don't have to write long names.

Order matters, style ids will be concatenated together in the order in which they appear in the rows of matrix.

Intention is to remove the dash between two style ids (just for demonstration purpose)
