### ISSUE TITLE
implement settings/persistent customization

### ISSUE THREAD

**Issue by pain-text-format** [pain-text-format/kksubs#49]
customize config.yaml using settings:

```
# config.yaml
...
settings:
  export: # name of command?
    destination: [custom destination]
```
